//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoowooTech.Passport.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_CLIENT
    {
        public int ID { get; set; }
        public string CLIENT_ID { get; set; }
        public string CLIENT_SECRET { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string HOSTS { get; set; }
        public short DELETED { get; set; }
    }
}
