//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoowooTech.Passport.Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APP_CLIENT> APP_CLIENT { get; set; }
        public DbSet<AUTH_TOKEN> AUTH_TOKEN { get; set; }
        public DbSet<OPERATE_LOG> OPERATE_LOG { get; set; }
        public DbSet<USER_ACCOUNT> USER_ACCOUNT { get; set; }
        public DbSet<USER_ACCOUNT_AGENT> USER_ACCOUNT_AGENT { get; set; }
        public DbSet<USER_ACCOUNT_GROUP> USER_ACCOUNT_GROUP { get; set; }
        public DbSet<USER_GROUP> USER_GROUP { get; set; }
        public DbSet<USER_GROUP_RIGHT> USER_GROUP_RIGHT { get; set; }
    }
}
