//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoowooTech.Passport.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACCOUNT_GROUP
    {
        public int ID { get; set; }
        public int ACCOUNT_ID { get; set; }
        public int GROUP_ID { get; set; }
        public short DELETED { get; set; }
    
        public virtual USER_ACCOUNT USER_ACCOUNT { get; set; }
        public virtual USER_GROUP USER_GROUP { get; set; }
    }
}
