//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoowooTech.Passport.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACCOUNT
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime LAST_LOGIN_TIME { get; set; }
        public string LAST_LOGIN_IP { get; set; }
        public short DELETED { get; set; }
        public short ROLE { get; set; }
        public string TRUENAME { get; set; }
    }
}
