
--
-- ACCOUNT
--
  CREATE TABLE "ACCOUNT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"USERNAME" VARCHAR2(128 CHAR) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CREATE_TIME" DATE DEFAULT sysdate
  NOT NULL ENABLE,
	"LAST_LOGIN_TIME" DATE NOT NULL ENABLE,
	"LAST_LOGIN_IP" VARCHAR2(20 CHAR),
	"DELETED" NUMBER(1,0) DEFAULT 0   NOT NULL ENABLE,
	"ROLE" NUMBER(5,0) NOT NULL ENABLE,
	"TRUENAME" VARCHAR2(32 CHAR),
	"STATUS" NUMBER(1,0) DEFAULT 0   NOT NULL ENABLE,
	"GROUPS" VARCHAR2(128),
	"DEPARTMENT_ID" NUMBER(10,0) DEFAULT 0   NOT NULL ENABLE,
	"PHONE" VARCHAR2(32 CHAR),
	"JOB" VARCHAR2(64 CHAR),
	"EMAIL" VARCHAR2(128 CHAR)
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- ACCOUNT_AGENT
--
  CREATE TABLE "ACCOUNT_AGENT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"ACCOUNT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"AGENT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"CREATE_TIME" DATE DEFAULT sysdate
  NOT NULL ENABLE,
	"DELETED" NUMBER(1,0) NOT NULL ENABLE
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- ACCOUNT_GROUP
--
  CREATE TABLE "ACCOUNT_GROUP" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"ACCOUNT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"GROUP_ID" NUMBER(10,0) NOT NULL ENABLE,
	"DELETED" NUMBER(1,0) NOT NULL ENABLE
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- APP_CLIENT
--
  CREATE TABLE "APP_CLIENT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"CLIENT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CLIENT_SECRET" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CREATE_TIME" DATE NOT NULL ENABLE,
	"HOSTS" VARCHAR2(256 CHAR) NOT NULL ENABLE,
	"DELETED" NUMBER(1,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(256 CHAR),
	"DEPARTMENT_ID" NUMBER DEFAULT 0   NOT NULL ENABLE
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- AUTH_TOKEN
--
  CREATE TABLE "AUTH_TOKEN" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"TOKEN" VARCHAR2(256 CHAR) NOT NULL ENABLE,
	"ACCOUNT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"CREATE_TIME" DATE DEFAULT sysdate
  NOT NULL ENABLE,
	"CLIENT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- DEPARTMENT
--
  CREATE TABLE "DEPARTMENT" 
   (	"ID" NUMBER(10,0) DEFAULT 0   NOT NULL ENABLE,
	"NAME" VARCHAR2(128 CHAR),
	"PARENT_ID" NUMBER(10,0) DEFAULT 0   NOT NULL ENABLE,
	"CREATE_TIME" DATE NOT NULL ENABLE,
	"DELETED" NUMBER(1,0) DEFAULT 0   NOT NULL ENABLE
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- GROUP
--
  CREATE TABLE "GROUP" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(64 CHAR) NOT NULL ENABLE,
	"DELETED" NUMBER(1,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(256 CHAR),
	"CREATE_TIME" DATE DEFAULT sysdate  NOT NULL ENABLE
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- GROUP_RIGHT
--
  CREATE TABLE "GROUP_RIGHT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"GROUP_ID" NUMBER(10,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(128 CHAR) NOT NULL ENABLE
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- OPERATE_LOG
--
  CREATE TABLE "OPERATE_LOG" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"ACCOUNT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"ACTION" VARCHAR2(256 CHAR) NOT NULL ENABLE,
	"CREATE_TIME" DATE NOT NULL ENABLE
   ) PCTFREE 10 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 );
--
-- IX_AGENT_ACCOUNT_ID
--
  CREATE INDEX "IX_AGENT_ACCOUNT_ID" ON "ACCOUNT_AGENT" ("ACCOUNT_ID")
  PCTFREE 10 INITRANS 2 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  );
--
-- IX_CLIENT_CLIENTID
--
  CREATE INDEX "IX_CLIENT_CLIENTID" ON "APP_CLIENT" ("CLIENT_ID")
  PCTFREE 10 INITRANS 2 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  );
--
-- IX_CLIENT_ACCOUNT_ID
--
  CREATE INDEX "IX_CLIENT_ACCOUNT_ID" ON "AUTH_TOKEN" ("ACCOUNT_ID","CLIENT_ID")
  PCTFREE 10 INITRANS 2 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  );
--
-- IX_TOKEN
--
  CREATE INDEX "IX_TOKEN" ON "AUTH_TOKEN" ("TOKEN")
  PCTFREE 10 INITRANS 2 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  );
--
-- IX_RIGHT_GROUPID
--
  CREATE INDEX "IX_RIGHT_GROUPID" ON "GROUP_RIGHT" ("GROUP_ID")
  PCTFREE 10 INITRANS 2 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  );
--
-- PK_ID
--
ALTER TABLE "ACCOUNT" ADD CONSTRAINT "PK_ID" PRIMARY KEY ("ID") ENABLE;

--
-- PK_AGENT_ID
--
ALTER TABLE "ACCOUNT_AGENT" ADD CONSTRAINT "PK_AGENT_ID" PRIMARY KEY ("ID") ENABLE;

--
-- PK_ACCOUNT_GROUPS_ID
--
ALTER TABLE "ACCOUNT_GROUP" ADD CONSTRAINT "PK_ACCOUNT_GROUPS_ID" PRIMARY KEY ("ID") ENABLE;

--
-- PK_CLIENT_ID
--
ALTER TABLE "APP_CLIENT" ADD CONSTRAINT "PK_CLIENT_ID" PRIMARY KEY ("ID") ENABLE;

--
-- PK_TOKEN_ID
--
ALTER TABLE "AUTH_TOKEN" ADD CONSTRAINT "PK_TOKEN_ID" PRIMARY KEY ("ID") ENABLE;

--
-- PK_DEPARTMENT_ID
--
ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT_ID" PRIMARY KEY ("ID") ENABLE;

--
-- SYS_C007818
--
ALTER TABLE "DEPARTMENT" ADD  CHECK ("NAME" IS NOT NULL) DISABLE VALIDATE;

--
-- PK_USERGROUP_ID
--
ALTER TABLE "GROUP" ADD CONSTRAINT "PK_USERGROUP_ID" PRIMARY KEY ("ID") ENABLE;

--
-- PK_RIGHT_ID
--
ALTER TABLE "GROUP_RIGHT" ADD CONSTRAINT "PK_RIGHT_ID" PRIMARY KEY ("ID") ENABLE;

--
-- PK_LOG_ID
--
ALTER TABLE "OPERATE_LOG" ADD CONSTRAINT "PK_LOG_ID" PRIMARY KEY ("ID") ENABLE;

--
-- FK_ACCOUNT_GROUPS_ACCOUNT_ID
--
ALTER TABLE "ACCOUNT_GROUP" ADD CONSTRAINT "FK_ACCOUNT_GROUPS_ACCOUNT_ID" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNT"("ID") ENABLE;

--
-- FK_ACCOUNT_GROUPS_GROUP_ID
--
ALTER TABLE "ACCOUNT_GROUP" ADD CONSTRAINT "FK_ACCOUNT_GROUPS_GROUP_ID" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP"("ID") ENABLE;

--
-- FK_GROUP_RIGHT_ID
--
ALTER TABLE "GROUP_RIGHT" ADD CONSTRAINT "FK_GROUP_RIGHT_ID" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP"("ID") ENABLE;

--
-- APP_CLIENT_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "APP_CLIENT_TRIGGER1"
  BEFORE INSERT ON "APP_CLIENT"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN
 select SEQ_CLIENT_ID.nextval
 into :new.id
 from sys.dual;

END;
/
--
-- AUTH_TOKEN_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "AUTH_TOKEN_TRIGGER1"
  BEFORE INSERT ON "AUTH_TOKEN"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN

 select SEQ_TOKEN_ID.nextval
 into :new.id
 from sys.dual;

END;
/
--
-- DEPARTMENT_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "DEPARTMENT_TRIGGER1"
  BEFORE INSERT ON "DEPARTMENT"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN

 select SEQ_DEPARTMENT_ID.nextval
 into :new.id
 from sys.dual;

END;
/
--
-- OPERATE_LOG_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "OPERATE_LOG_TRIGGER1"
  BEFORE INSERT ON "OPERATE_LOG"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN

 select SEQ_LOG_ID.nextval
 into :new.id
 from sys.dual;

END;
/
--
-- USER_ACCOUNT_AGENT_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "USER_ACCOUNT_AGENT_TRIGGER1"
  BEFORE INSERT ON "ACCOUNT_AGENT"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN

 select SEQ_COMMON_ID.nextval
 into :new.id
 from sys.dual;

END;
/
--
-- USER_ACCOUNT_GROUP_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "USER_ACCOUNT_GROUP_TRIGGER1"
  BEFORE INSERT ON "ACCOUNT_GROUP"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN

 select SEQ_COMMON_ID.nextval
 into :new.id
 from sys.dual;

END;
/
--
-- USER_ACCOUNT_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "USER_ACCOUNT_TRIGGER1"
  BEFORE INSERT ON "ACCOUNT"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN 
 select SEQ_ACCOUNT_ID.nextval
 into :new.id
 from sys.dual;
END;
/
--
-- USER_GROUP_RIGHT_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "USER_GROUP_RIGHT_TRIGGER1"
  BEFORE INSERT ON "GROUP_RIGHT"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN

 select SEQ_COMMON_ID.nextval
 into :new.id
 from sys.dual;

END;
/
--
-- USER_GROUP_TRIGGER1
--
  CREATE OR REPLACE TRIGGER "USER_GROUP_TRIGGER1"
  BEFORE INSERT ON "GROUP"
  REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
BEGIN

 select SEQ_GROUP_ID.nextval
 into :new.id
 from sys.dual;

END;
/
